name = "blog"
version = "0.1.0"

[[lean_lib]]
name = "_drafts"
precompileModules = true
supportInterpreter = true

#[[require]]
#name = "smt"
#scope = "ufmg-smite"
#rev = "main"

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.28.0"

#[[require]]
#name = "SSA"
#git = "https://github.com/opencompl/lean-mlir"
#rev = "main"

# [[require]]
# name = "mdgen"
# scope = "seasawher"
# rev = "main"
